# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 21:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import web.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
                ('corpus_tag', models.TextField()),
                ('details', models.TextField()),
            ],
            options={
                'db_table': 'submission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubmissionLink',
            fields=[
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, to='web.Submission')),
                ('doc_id', models.TextField(primary_key=True)),
                ('mention_id', web.fields.SpanField(primary_key=True, serialize=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('link_name', models.TextField()),
                ('confidence', models.FloatField()),
            ],
            options={
                'db_table': 'submission_link',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubmissionMention',
            fields=[
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, to='web.Submission')),
                ('doc_id', models.TextField(primary_key=True)),
                ('mention_id', web.fields.SpanField(primary_key=True, serialize=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('canonical_id', web.fields.SpanField()),
                ('mention_type', models.TextField()),
                ('gloss', models.TextField()),
            ],
            options={
                'db_table': 'submission_mention',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubmissionRelation',
            fields=[
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, to='web.Submission')),
                ('doc_id', models.TextField(primary_key=True)),
                ('subject_id', web.fields.SpanField(primary_key=True, serialize=False)),
                ('object_id', web.fields.SpanField(primary_key=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('relation', models.TextField()),
                ('subject_gloss', models.TextField()),
                ('object_gloss', models.TextField()),
                ('confidence', models.FloatField()),
            ],
            options={
                'db_table': 'submission_relation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubmissionScore',
            fields=[
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='web.Submission')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('score_type', models.TextField()),
                ('score', web.fields.ScoreField()),
            ],
            options={
                'db_table': 'submission_score',
                'managed': False,
            },
        ),
    ]
