# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 02:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_document_documenttag_evaluationbatch_evaluationlink_evaluationlinkresponse_evaluationmention_evaluat'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionState',
            fields=[
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='web.Submission')),
                ('status', models.TextField(default='pending-upload')),
                ('message', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionUser',
            fields=[
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='web.Submission')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
