# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 02:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_submissionstate_submissionuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
